update
install ack
install autojump
install bash
install bash-completion
install ctags
install direnv
install git
install grc
install postgresql
install rbenv
install reattach-to-user-namespace
install ruby-build
install ssh-copy-id
install the_silver_searcher
install tmux
install tree
install vim
install wget
