export CLICOLOR=true

# Colour lookups
BLACK='a'
RED='b'
GREEN='c'
BROWN='d'
BLUE='e'
MAGENTA='f'
CYAN='g'
LIGHT_GREY='h'
BOLD_BLACK='A'
BOLD_RED='B'
BOLD_GREEN='C'
BOLD_BROWN='D'
BOLD_BLUE='E'
BOLD_MAGENTA='F'
BOLD_CYAN='G'
BOLD_LIGHT_GREY='H'
DEFAULT='x'

# Colours are foreground/background
LS_DIRECTORY="$CYAN$DEFAULT"
LS_SYMBOLIC_LINK="$GREEN$DEFAULT"
LS_SOCKET="$BROWN$DEFAULT"
LS_PIPE="$BROWN$LIGHT_GREY"
LS_EXECUTABLE="$RED$DEFAULT"
LS_BLOCK_SPECIAL="$BLUE$CYAN"
LS_CHARACTER_SPECIAL="$CYAN$BROWN"
LS_EXECUTABLE_SETUID="$MAGENTA$LIGHT_GREY"
LS_EXECUTABLE_SETGID="$MAGENTA$CYAN"
LS_DIRECTORY_STICKY_WRITABLE="$BLACK$GREEN"
LS_DIRECTORY_UNSTICKY_WRITABLE="$BLACK$BROWN"

# Split for legibility, these elements must appear in this order
FIRST="$LS_DIRECTORY$LS_SYMBOLIC_LINK$LS_SOCKET$LS_PIPE$LS_EXECUTABLE$LS_BLOCK_SPECIAL$LS_CHARACTER_SPECIAL"
SECOND="$LS_EXECUTABLE_SETUID$LS_EXECUTABLE_SETGID$LS_DIRECTORY_STICKY_WRITABLE$LS_DIRECTORY_UNSTICKY_WRITABLE"
export LSCOLORS="$FIRST$SECOND"

alias ll='ls -lahG'
